app = "waterpurifierluna"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  # APP_KEY lo pondremos con fly secrets más adelante
  APP_URL = "https://waterpurifierluna.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true

[[statics]]
  guest_path = "/var/www/html/public"
  url_prefix = "/"

[[mounts]]
  source = "storage"
  destination = "/var/www/html/storage"
